### ISSUE TITLE
Python Driver for Sensirion Sgp40

### ISSUE THREAD

**Issue by ImanolGo** [Sensirion/python-shdlc-svm40#1]
Hi Sensirion Team,

From the specs is fairly easy to read the raw air quality values, but the algorithm to turn it into VOC is only ported to C.

Are you planning to also provide a driver also for the Sgp40 for Python?

**Comment by MBjoern** [comment]
I've seen you've already successfully tested this python port of the [VOC algorithm](https://github.com/DFRobot/DFRobot_SGP40/tree/master/Python/raspberrypi)

Enjoy your SGP40! I'm looking forward to hearing about the great use cases you'll discover for it.
